name: gha-commands-tutorial
on: [push]
jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: setting error message
        run: echo "::error:: Semicolon Missing"
      - name: setting error message with params
        run: echo "::error, title=Error with Params, file=test.js, line=2, endLine=3, col=5, endColumn=6::Missing Semicolon"
      - name: setting Debug message with params
        run: echo "::debug, title=Debug with Params, file=test.js, line=2, endLine=3, col=5, endColumn=6::Missing Semicolon"
      - name: setting Warning message with params
        run: echo "::warning, title=Warning with Params, file=test.js, line=2, endLine=3, col=5, endColumn=6::Missing Semicolon"
      - name: setting Notice message with params
        run: echo "::notice, title=Notice with Params, file=test.js, line=2, endLine=3, col=5, endColumn=6::Missing Semicolon"
      - name: Masking Value
        run: echo "::add-mask:: Secret"
      - name: Echo Masking Value
        run: echo "Secret"