name: List Files and Checkout
on: [push]
jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout Using Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Amey
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Checkout GIT Repo
        run: |
          git init 
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files After
        run: ls -a