name: PR-Adding-Comment
on:
  pull_request_target:
    types: [opened]

jobs:
  PR-Add-Comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            owner: context.repo.owner,  
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "Thanks for Contribution"
           });

